export {
  TERMINAL_MIN_HEIGHT,
  createAnnotatedTagInTerminal,
  createLightweightTagInTerminal,
  feedTerminalOutput,
  flushPendingCommands,
  gitJugglerTerminalCommand,
  markTerminalOutputReceived,
  noteTerminalOutput,
  openTerminal,
  pushingRepos,
  pushingTargetCommits,
  registerTerminalSender,
  runInTerminal,
  setTerminalHeight,
  shellQuote,
  shouldConnectTerminal,
  startFetch,
  startPush,
  stopFetch,
  stopPush,
  terminalHeight,
  terminalOpen,
  terminalShell,
  toggleTerminalOpen,
  unregisterTerminalSender,
} from "./storeCore";
